# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grSim_Replacement.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17grSim_Replacement.proto\"[\n\x16grSim_RobotReplacement\x12\t\n\x01x\x18\x01 \x02(\x01\x12\t\n\x01y\x18\x02 \x02(\x01\x12\x0b\n\x03\x64ir\x18\x03 \x02(\x01\x12\n\n\x02id\x18\x04 \x02(\r\x12\x12\n\nyellowteam\x18\x05 \x02(\x08\"E\n\x15grSim_BallReplacement\x12\t\n\x01x\x18\x01 \x02(\x01\x12\t\n\x01y\x18\x02 \x02(\x01\x12\n\n\x02vx\x18\x03 \x02(\x01\x12\n\n\x02vy\x18\x04 \x02(\x01\"b\n\x11grSim_Replacement\x12$\n\x04\x62\x61ll\x18\x01 \x01(\x0b\x32\x16.grSim_BallReplacement\x12\'\n\x06robots\x18\x02 \x03(\x0b\x32\x17.grSim_RobotReplacement')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grSim_Replacement_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_GRSIM_ROBOTREPLACEMENT']._serialized_start=27
  _globals['_GRSIM_ROBOTREPLACEMENT']._serialized_end=118
  _globals['_GRSIM_BALLREPLACEMENT']._serialized_start=120
  _globals['_GRSIM_BALLREPLACEMENT']._serialized_end=189
  _globals['_GRSIM_REPLACEMENT']._serialized_start=191
  _globals['_GRSIM_REPLACEMENT']._serialized_end=289
# @@protoc_insertion_point(module_scope)
