# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ui_messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11ui_messages.proto\x12\nUIMessages\"\x96\x05\n\rEnginePackage\x12.\n\x05scene\x18\x01 \x01(\x0b\x32\x1f.UIMessages.EnginePackage.Scene\x12?\n\x0e\x61i_environment\x18\x02 \x01(\x0b\x32\'.UIMessages.EnginePackage.AIEnvironment\x12\x0b\n\x03\x66ps\x18\x03 \x01(\r\x1a\xda\x02\n\x05Scene\x12\x32\n\x04\x62\x61ll\x18\x01 \x01(\x0b\x32$.UIMessages.EnginePackage.Scene.Ball\x12<\n\ryellow_robots\x18\x02 \x03(\x0b\x32%.UIMessages.EnginePackage.Scene.Robot\x12:\n\x0b\x62lue_robots\x18\x03 \x03(\x0b\x32%.UIMessages.EnginePackage.Scene.Robot\x1a\'\n\x04\x42\x61ll\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x1az\n\x05Robot\x12\n\n\x02id\x18\x01 \x01(\r\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\x13\n\x0borientation\x18\x04 \x01(\x02\x12\x12\n\x05vel_x\x18\x05 \x01(\x02H\x00\x88\x01\x01\x12\x12\n\x05vel_y\x18\x06 \x01(\x02H\x01\x88\x01\x01\x42\x08\n\x06_vel_xB\x08\n\x06_vel_y\x1a\xa9\x01\n\rAIEnvironment\x12\x0c\n\x04name\x18\x01 \x01(\t\x12T\n\x12robot_destinations\x18\x02 \x03(\x0b\x32\x38.UIMessages.EnginePackage.AIEnvironment.RobotDestination\x1a\x34\n\x10RobotDestination\x12\n\n\x02id\x18\x01 \x01(\r\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\"\xaa\x02\n\x07\x43ommand\x12\x35\n\x0c\x63ommand_type\x18\x01 \x01(\x0e\x32\x1f.UIMessages.Command.CommandType\x12\x11\n\trobot_ids\x18\x02 \x03(\r\x12\x36\n\x0b\x64\x65stination\x18\x04 \x01(\x0b\x32\x1c.UIMessages.Command.PositionH\x00\x88\x01\x01\x12\x1b\n\x0e\x61i_environment\x18\x05 \x01(\tH\x01\x88\x01\x01\x1a \n\x08Position\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\";\n\x0b\x43ommandType\x12\x11\n\rSTART_MOVE_TO\x10\x00\x12\x19\n\x15\x43HANGE_AI_ENVIRONMENT\x10\x01\x42\x0e\n\x0c_destinationB\x11\n\x0f_ai_environmentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ui_messages_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ENGINEPACKAGE']._serialized_start=34
  _globals['_ENGINEPACKAGE']._serialized_end=696
  _globals['_ENGINEPACKAGE_SCENE']._serialized_start=178
  _globals['_ENGINEPACKAGE_SCENE']._serialized_end=524
  _globals['_ENGINEPACKAGE_SCENE_BALL']._serialized_start=361
  _globals['_ENGINEPACKAGE_SCENE_BALL']._serialized_end=400
  _globals['_ENGINEPACKAGE_SCENE_ROBOT']._serialized_start=402
  _globals['_ENGINEPACKAGE_SCENE_ROBOT']._serialized_end=524
  _globals['_ENGINEPACKAGE_AIENVIRONMENT']._serialized_start=527
  _globals['_ENGINEPACKAGE_AIENVIRONMENT']._serialized_end=696
  _globals['_ENGINEPACKAGE_AIENVIRONMENT_ROBOTDESTINATION']._serialized_start=644
  _globals['_ENGINEPACKAGE_AIENVIRONMENT_ROBOTDESTINATION']._serialized_end=696
  _globals['_COMMAND']._serialized_start=699
  _globals['_COMMAND']._serialized_end=997
  _globals['_COMMAND_POSITION']._serialized_start=869
  _globals['_COMMAND_POSITION']._serialized_end=901
  _globals['_COMMAND_COMMANDTYPE']._serialized_start=903
  _globals['_COMMAND_COMMANDTYPE']._serialized_end=962
# @@protoc_insertion_point(module_scope)
